# --- graph mix specific parameters --- last load

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 108000 # num_episode * simulation_time / delta_time / 2

runner: "episode"

buffer_size: 300

# update the target network every {} episodes
target_update_interval: 50

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "graphmix"
mixing_embed_dim: [64]
hypernet_layers: 2
hypernet_embed: 64
adj_mask_file: maps/jinan12/anon_3_4_jinan_real.csv
full_attn: False
temperature_k: 0.5

# local loss coefficient
lambda_local: 1

# Frequency to record attention score to csv file
record_attention_interval: 5

name: "graphmix"
